{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flymon.fullname" . }}-gateway
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flymon.gateway.labels" . | nindent 4 }}
  {{- with .Values.gateway.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: {{ .Values.gateway.service.portName }}
      port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.targetPort }}
      protocol: TCP
      {{- if and (or (eq .Values.gateway.service.type "NodePort") (eq .Values.gateway.service.type "LoadBalancer")) .Values.gateway.service.nodePort }}
      nodePort: {{ .Values.gateway.service.nodePort }}
      {{- end }}
  selector: {{- include "flymon.gateway.selectorLabels" . | nindent 4 }}
{{- end }}
